# Generated by Django 5.1.2 on 2024-10-28 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='binaries/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('short_desc', models.TextField(default='No detailed description available.')),
                ('long_desc', models.TextField(default='No detailed description available.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='program_images/')),
            ],
        ),
        migrations.CreateModel(
            name='STLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stl_file', models.FileField(upload_to='stl_models/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('binary_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='sedlowebapp.binaryfile')),
            ],
        ),
    ]
