# Generated by Django 5.1.2 on 2024-10-28 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SedloWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('zip_file', models.FileField(upload_to='telegrams/zips/')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.AlterField(
            model_name='binaryfile',
            name='long_desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='binaryfile',
            name='short_desc',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='TelegramPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='telegrams/pdfs/')),
                ('telegram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='SedloWebApp.telegram')),
            ],
        ),
    ]
